name: Feature request
description: File a feature request.
title: "[Feature]: "
labels: ["feature"]
projects: ["opentalaria"]
assignees:
  - vladoatanasov
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: story-description
    attributes:
      label: Description
      description: Please describe in detail the feature you want implemented
      placeholder: Description
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
