// protocol has been generated from message format json - DO NOT EDIT
package protocol

import (
	uuid "github.com/google/uuid"
	"time"
)

// TopicPartitions_ConsumerGroupHeartbeatResponse contains a
type TopicPartitions_ConsumerGroupHeartbeatResponse struct {
	// Version defines the protocol version to use for encode and decode
	Version int16
	// TopicID contains the topic ID.
	TopicID uuid.UUID
	// Partitions contains the partitions.
	Partitions []int32
}

func (t *TopicPartitions_ConsumerGroupHeartbeatResponse) encode(pe packetEncoder, version int16) (err error) {
	t.Version = version
	if err := pe.putUUID(t.TopicID); err != nil {
		return err
	}

	if err := pe.putInt32Array(t.Partitions); err != nil {
		return err
	}

	pe.putUVarint(0)
	return nil
}

func (t *TopicPartitions_ConsumerGroupHeartbeatResponse) decode(pd packetDecoder, version int16) (err error) {
	t.Version = version
	if t.TopicID, err = pd.getUUID(); err != nil {
		return err
	}

	if t.Partitions, err = pd.getInt32Array(); err != nil {
		return err
	}

	if _, err = pd.getEmptyTaggedFieldArray(); err != nil {
		return err
	}
	return nil
}

// Assignment contains a null if not provided; the assignment otherwise.
type Assignment struct {
	// Version defines the protocol version to use for encode and decode
	Version int16
	// Error contains the assigned error.
	Error int8
	// AssignedTopicPartitions contains the partitions assigned to the member that can be used immediately.
	AssignedTopicPartitions []TopicPartitions_ConsumerGroupHeartbeatResponse
	// PendingTopicPartitions contains the partitions assigned to the member that cannot be used because they are not released by their former owners yet.
	PendingTopicPartitions []TopicPartitions_ConsumerGroupHeartbeatResponse
	// MetadataVersion contains the version of the metadata.
	MetadataVersion int16
	// MetadataBytes contains the assigned metadata.
	MetadataBytes []byte
}

func (a *Assignment) encode(pe packetEncoder, version int16) (err error) {
	a.Version = version
	pe.putInt8(a.Error)

	if err := pe.putArrayLength(len(a.AssignedTopicPartitions)); err != nil {
		return err
	}
	for _, block := range a.AssignedTopicPartitions {
		if err := block.encode(pe, a.Version); err != nil {
			return err
		}
	}

	if err := pe.putArrayLength(len(a.PendingTopicPartitions)); err != nil {
		return err
	}
	for _, block := range a.PendingTopicPartitions {
		if err := block.encode(pe, a.Version); err != nil {
			return err
		}
	}

	pe.putInt16(a.MetadataVersion)

	if err := pe.putBytes(a.MetadataBytes); err != nil {
		return err
	}

	pe.putUVarint(0)
	return nil
}

func (a *Assignment) decode(pd packetDecoder, version int16) (err error) {
	a.Version = version
	if a.Error, err = pd.getInt8(); err != nil {
		return err
	}

	var numAssignedTopicPartitions int
	if numAssignedTopicPartitions, err = pd.getArrayLength(); err != nil {
		return err
	}
	if numAssignedTopicPartitions > 0 {
		a.AssignedTopicPartitions = make([]TopicPartitions_ConsumerGroupHeartbeatResponse, numAssignedTopicPartitions)
		for i := 0; i < numAssignedTopicPartitions; i++ {
			var block TopicPartitions_ConsumerGroupHeartbeatResponse
			if err := block.decode(pd, a.Version); err != nil {
				return err
			}
			a.AssignedTopicPartitions[i] = block
		}
	}

	var numPendingTopicPartitions int
	if numPendingTopicPartitions, err = pd.getArrayLength(); err != nil {
		return err
	}
	if numPendingTopicPartitions > 0 {
		a.PendingTopicPartitions = make([]TopicPartitions_ConsumerGroupHeartbeatResponse, numPendingTopicPartitions)
		for i := 0; i < numPendingTopicPartitions; i++ {
			var block TopicPartitions_ConsumerGroupHeartbeatResponse
			if err := block.decode(pd, a.Version); err != nil {
				return err
			}
			a.PendingTopicPartitions[i] = block
		}
	}

	if a.MetadataVersion, err = pd.getInt16(); err != nil {
		return err
	}

	if a.MetadataBytes, err = pd.getBytes(); err != nil {
		return err
	}

	if _, err = pd.getEmptyTaggedFieldArray(); err != nil {
		return err
	}
	return nil
}

type ConsumerGroupHeartbeatResponse struct {
	// Version defines the protocol version to use for encode and decode
	Version int16
	// ThrottleTimeMs contains the duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota.
	ThrottleTimeMs int32
	// ErrorCode contains the top-level error code, or 0 if there was no error
	ErrorCode int16
	// ErrorMessage contains the top-level error message, or null if there was no error.
	ErrorMessage *string
	// MemberID contains the member id generated by the coordinator. Only provided when the member joins with MemberEpoch == 0.
	MemberID *string
	// MemberEpoch contains the member epoch.
	MemberEpoch int32
	// ShouldComputeAssignment contains a True if the member should compute the assignment for the group.
	ShouldComputeAssignment bool
	// HeartbeatIntervalMs contains the heartbeat interval in milliseconds.
	HeartbeatIntervalMs int32
	// Assignment contains a null if not provided; the assignment otherwise.
	Assignment Assignment
}

func (r *ConsumerGroupHeartbeatResponse) encode(pe packetEncoder) (err error) {
	pe = FlexibleEncoderFrom(pe)
	pe.putInt32(r.ThrottleTimeMs)

	pe.putInt16(r.ErrorCode)

	if err := pe.putNullableString(r.ErrorMessage); err != nil {
		return err
	}

	if err := pe.putNullableString(r.MemberID); err != nil {
		return err
	}

	pe.putInt32(r.MemberEpoch)

	pe.putBool(r.ShouldComputeAssignment)

	pe.putInt32(r.HeartbeatIntervalMs)

	if err := r.Assignment.encode(pe, r.Version); err != nil {
		return err
	}

	pe.putUVarint(0)
	return nil
}

func (r *ConsumerGroupHeartbeatResponse) decode(pd packetDecoder, version int16) (err error) {
	r.Version = version
	pd = FlexibleDecoderFrom(pd)
	if r.ThrottleTimeMs, err = pd.getInt32(); err != nil {
		return err
	}

	if r.ErrorCode, err = pd.getInt16(); err != nil {
		return err
	}

	if r.ErrorMessage, err = pd.getNullableString(); err != nil {
		return err
	}

	if r.MemberID, err = pd.getNullableString(); err != nil {
		return err
	}

	if r.MemberEpoch, err = pd.getInt32(); err != nil {
		return err
	}

	if r.ShouldComputeAssignment, err = pd.getBool(); err != nil {
		return err
	}

	if r.HeartbeatIntervalMs, err = pd.getInt32(); err != nil {
		return err
	}

	tmpAssignment := Assignment{}
	if err := tmpAssignment.decode(pd, r.Version); err != nil {
		return err
	}
	r.Assignment = tmpAssignment

	if _, err = pd.getEmptyTaggedFieldArray(); err != nil {
		return err
	}
	return nil
}

func (r *ConsumerGroupHeartbeatResponse) GetKey() int16 {
	return 68
}

func (r *ConsumerGroupHeartbeatResponse) GetVersion() int16 {
	return r.Version
}

func (r *ConsumerGroupHeartbeatResponse) GetHeaderVersion() int16 {
	return 1
}

func (r *ConsumerGroupHeartbeatResponse) IsValidVersion() bool {
	return r.Version == 0
}

func (r *ConsumerGroupHeartbeatResponse) GetRequiredVersion() int16 {
	// TODO - it isn't possible to determine this from the message format json files
	return 0
}

func (r *ConsumerGroupHeartbeatResponse) throttleTime() time.Duration {
	return time.Duration(r.ThrottleTimeMs) * time.Millisecond
}
